git-debimport grub2_1.99-27+deb7u2.diff.gz

diff --git a/debian/patches/grub.cfg_400.patch b/debian/patches/grub.cfg_400.patch
--- a/debian/patches/grub.cfg_400.patch
+++ b/debian/patches/grub.cfg_400.patch
@@ -2,14 +2,14 @@ Index: b/util/grub-mkconfig.in
 ===================================================================
 --- a/util/grub-mkconfig.in
 +++ b/util/grub-mkconfig.in
-@@ -313,6 +313,10 @@
+@@ -293,6 +293,10 @@
    esac
  done
  
-+if [ "x${grub_cfg}" != "x" ] && ! grep -q "^password " ${grub_cfg}.new ; then
++if [ "x${grub_cfg}" != "x" ] && ! grep "^password " ${grub_cfg}.new >/dev/null; then
 +  chmod 444 ${grub_cfg}.new || true
 +fi
 +
  if test "x${grub_cfg}" != "x" ; then
-   # none of the children aborted with error, install the new grub.cfg
-   mv -f ${grub_cfg}.new ${grub_cfg}
+   if ! ${grub_script_check} ${grub_cfg}.new; then
+     echo "Syntax errors are detected in generated GRUB config file." >&2
diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -17,6 +17,29 @@ merge_debconf_into_conf()
   fi
 }
 
+get_wubi_device()
+{
+  if [ ! -x /usr/share/lupin-support/grub-mkimage ] || \
+     ! /usr/share/lupin-support/grub-mkimage --test; then
+    return 1
+  fi
+
+  local bootdev="$(grub-probe --target=device /boot)" || true
+  local loop_file=
+  case $bootdev in
+    /dev/loop/*|/dev/loop[0-9])
+      loop_file="$(losetup "$bootdev" | sed -e "s/^[^(]*(\([^)]\+\)).*/\1/")"
+      # If it's loop-mounted from another device, it isn't Wubi.
+      case $loop_file in
+        /dev/*) return 1 ;;
+      esac
+    ;;
+    *) return 1 ;;
+  esac
+
+  echo "$bootdev"
+}
+
 # This only works on a Linux system with udev running.  This is probably the
 # vast majority of systems where we need any of this, though, and we fall
 # back reasonably gracefully if we don't have it.
@@ -149,11 +172,12 @@ sysfs_size()
 # for kFreeBSD
 camcontrol_size()
 {
-  local num_sectors sector_size size
+  local num_sectors sector_size size=
 
-  num_sectors="$(camcontrol readcap "$1" -q -s -N)"
-  sector_size="$(camcontrol readcap "$1" -q -b)"
-  size="$(expr "$num_sectors" \* "$sector_size" / 1000 / 1000)"
+  if num_sectors="$(camcontrol readcap "$1" -q -s -N)"; then
+    sector_size="$(camcontrol readcap "$1" -q -b)"
+    size="$(expr "$num_sectors" \* "$sector_size" / 1000 / 1000)"
+  fi
 
   [ "$size" ] || size='???'
   echo "$size"
@@ -255,9 +279,26 @@ get_mountpoint()
   echo "${boot_mountpoint:-/}"
 }
 
+config_item()
+{
+  if [ -f /etc/default/grub ]; then
+    . /etc/default/grub || return
+  fi
+  eval echo "\$$1"
+}
+
 case "$1" in
   configure)
     . /usr/share/debconf/confmodule
+
+    if dpkg --compare-versions "$2" lt-nl 1.99-1; then
+      # Force dpkg to replace this directory with a symlink.
+      if [ ! -L /usr/share/doc/@PACKAGE@ ] && [ -d /usr/share/doc/@PACKAGE@ ]; then
+        if rmdir /usr/share/doc/@PACKAGE@ 2>/dev/null; then
+          ln -sf grub-common /usr/share/doc/@PACKAGE@
+        fi
+      fi
+    fi
 
     devicemap_regenerated=
 
@@ -290,10 +331,18 @@ case "$1" in
       # whole it's less risky to move to /dev/disk/by-id/.
       devicemap_lines="$(egrep -v '^[[:space:]]+#' /boot/grub/device.map | wc -l)"
       grub-mkdevicemap --no-floppy
+      devicemap_regenerated=1
       if test "$devicemap_lines" != 1; then
         db_input critical grub2/device_map_regenerated || true
         db_go || true
       fi
+    fi
+
+    if test -z "$devicemap_regenerated" && \
+       dpkg --compare-versions "$2" lt-nl 1.99~20101210-2 && \
+       grep -qs /md-uuid- /boot/grub/device.map; then
+      echo "Removing MD devices from device.map, since the BIOS cannot read from these." >&2
+      sed -i '/\/md-uuid-/d' /boot/grub/device.map
     fi
 
     tmp_default_grub="$(mktemp -t grub.XXXXXXXXXX)"
@@ -350,6 +399,18 @@ case "$1" in
           fi
         fi
 
+        # Make sure that Wubi users never see confusing device prompts.
+        # Wubi is a very specialised hack that does complicated things with
+        # grub-install diversions to create an image that's chained from the
+        # Windows boot loader to boot an operating system from a file on a
+        # Windows file system.  In these circumstances, prompting for where
+        # to install GRUB is not going to help anyone.
+        wubi_device="$(get_wubi_device)" || true
+        if [ "$wubi_device" ]; then
+          db_set grub-pc/install_devices "$wubi_device"
+          db_fset grub-pc/install_devices seen true
+        fi
+
         if test -e /boot/grub/stage2 && test -e /boot/grub/menu.lst && \
            ! test -e /boot/grub/grub2-installed && \
            test -z "$UPGRADE_FROM_GRUB_LEGACY"; then
@@ -371,15 +432,16 @@ case "$1" in
             # We just hooked GRUB 2 in menu.lst; then also generate grub.cfg.
             touch /boot/grub/grub.cfg
           fi
-        else
+        elif test -z "$2" || test -e /boot/grub/core.img || \
+             test "$UPGRADE_FROM_GRUB_LEGACY" || test "$wubi_device"; then
           question=grub-pc/install_devices
           device_map="$(grub-mkdevicemap -m - | grep -v '^(fd[0-9]\+)' || true)"
           devices="$(echo "$device_map" | cut -f2)"
           if dpkg --compare-versions "$2" lt 1.98+20100702-1 && \
-             test "$(uname -s)" = Linux; then
+             test "$(uname -s)" = Linux && [ -z "$wubi_device" ]; then
             # Migrate to new by-id naming scheme.
             db_get grub-pc/install_devices
-            old_devices="$RET"
+            old_devices="$(echo "$RET" | sed 's/, / /g')"
             new_devices=
             # Common-case optimisation: if the list of devices is
             # identical to the LHS of grub-mkdevicemap's output, then
@@ -435,7 +497,7 @@ case "$1" in
             db_get grub-pc/install_devices
             valid=1
             for device in $RET; do
-              if [ ! -e "$device" ]; then
+              if [ ! -e "${device%,}" ]; then
                 valid=0
                 break
               fi
@@ -492,7 +554,7 @@ case "$1" in
             db_go
             db_get "$question"
             failed_devices=
-            for i in `echo $RET | sed -e 's/,/ /g'` ; do
+            for i in `echo $RET | sed -e 's/, / /g'` ; do
               real_device="$(readlink -f "$i")"
               if grub-install --force --no-floppy $real_device ; then
                 # We just installed GRUB 2; then also generate grub.cfg.
@@ -587,6 +649,26 @@ case "$1" in
           # removed, we don't need this any more.
           rm -f /boot/grub/grub2-installed
         fi
+      ;;
+
+      grub-efi-ia32|grub-efi-amd64)
+        bootloader_id="$(config_item GRUB_DISTRIBUTOR | tr A-Z a-z | \
+                         cut -d' ' -f1)"
+        if [ "$bootloader_id" ] && [ -d "/boot/efi/EFI/$bootloader_id" ]; then
+          grub-install
+        fi
+
+        # /boot/grub/ has more chances of being accessible by GRUB
+        for i in /usr/share/grub/unicode.pf2 ; do
+          if test -e $i ; then
+            mkdir -p /boot/grub
+            cp $i /boot/grub/
+          fi
+        done
+      ;;
+
+      grub-yeeloong)
+        grub-install
       ;;
     esac
 
